# Generated by Django 5.0.6 on 2024-06-02 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PowerConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('wind_speed', models.FloatField()),
                ('general_diffuse_flows', models.FloatField()),
                ('diffuse_flows', models.FloatField()),
                ('zone_1_power_consumption', models.FloatField()),
                ('zone_2_power_consumption', models.FloatField()),
                ('zone_3_power_consumption', models.FloatField()),
                ('hour', models.IntegerField(blank=True, null=True)),
                ('dayofweek', models.IntegerField(blank=True, null=True)),
                ('quarter', models.IntegerField(blank=True, null=True)),
                ('month', models.IntegerField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('dayofyear', models.IntegerField(blank=True, null=True)),
                ('day', models.IntegerField(blank=True, null=True)),
                ('is_weekend', models.BooleanField(default=False)),
                ('zone_1_power_consumption_lag_1', models.FloatField(blank=True, null=True)),
                ('zone_1_power_consumption_lag_2', models.FloatField(blank=True, null=True)),
                ('zone_1_power_consumption_rolling_mean_3', models.FloatField(blank=True, null=True)),
                ('zone_1_power_consumption_rolling_std_3', models.FloatField(blank=True, null=True)),
                ('zone_1_power_consumption_ema_3', models.FloatField(blank=True, null=True)),
                ('zone_2_power_consumption_lag_1', models.FloatField(blank=True, null=True)),
                ('zone_2_power_consumption_lag_2', models.FloatField(blank=True, null=True)),
                ('zone_2_power_consumption_rolling_mean_3', models.FloatField(blank=True, null=True)),
                ('zone_2_power_consumption_rolling_std_3', models.FloatField(blank=True, null=True)),
                ('zone_2_power_consumption_ema_3', models.FloatField(blank=True, null=True)),
                ('zone_3_power_consumption_lag_1', models.FloatField(blank=True, null=True)),
                ('zone_3_power_consumption_lag_2', models.FloatField(blank=True, null=True)),
                ('zone_3_power_consumption_rolling_mean_3', models.FloatField(blank=True, null=True)),
                ('zone_3_power_consumption_rolling_std_3', models.FloatField(blank=True, null=True)),
                ('zone_3_power_consumption_ema_3', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
